services:
  - docker
script: make test
notifications:
  on_success: always
  on_failure: always
  slack:
    - secure: "nrkgdEZ81/vRsbOLBIM/Gz0JJ6p4SundgwBn0lx47IAm4eea9gaMyk5hsZcsNClbvzFkZhehkO5y/w63sKIguBRlnKmJJ4jf6und9mwrv5GVfS9Z8KvGEnE3J8XYzaTGrabYVe9QqIiTqdpgkWtdYyvxWdQIqIj4wCpLSmZ/hoF66swpLkjPV/8XvMm6vXnEdXqPQVx54Up/j+xjzVV0GiP5Zl6bJEfmnpjo83qvohPs+sTmZpLITNzoik7DFFl2PY9eAnct+fJltvm1jLWdG9FN+1ULSQyMZndAF2/m+Qug/Ypb7QUP5DIpMW4waX/8qk9+w1kK+s/MX2q0vyXghJN2QIKA2H5y85WH/CpmSwebkZPAfCRzq1FH6TWjOmr5ZxLwc9pTKYygKAKSCDoetwCL8a/jHpz+jlZXQPMn1evkihmncyk0cRXDl6ZxEd8JR9yTiHWRAmebypWrAqAAWD8rRGO9jSHDzykTetx6zGiAVglBLV6UVAEpJgU2gwymFo4PZMyNlZXjwDDjYxjB6qdEYxEHvD7rEwyi/r9a2UrYI4j6GMeF/hWvL1PDfzTg4ODXAekyoWoaN32nHjkr1YJEEOAGDIIVaqcIdeyYIdgwl84In+7VUimo59yKUfTzJBxBBLaLphCN8Fow19d4XOpbgEva5Rj3OggAmHjpTEw="
