version: '3'
services:
  webapp:
    build: ./docker/webapp
    ports:
      - '8080:8080'
    environment:
      - SEARCH_HOST=search.home
      - RACK_ENV=development
    volumes:
      - ./docker/webapp:/wrk
    networks:
      mesh:
        aliases:
          - webapp.home
  
  search:
    build: ./docker/search
    environment:
      - discovery.type=single-node
      - indices.fielddata.cache.size=0
    networks:
      mesh:
        aliases:
          - search.home

  zeppelin:
    build: ./docker/zeppelin
    command: ./bin/zeppelin.sh
    ports:
      - 8888:8080
    environment:
      - ZEPPELIN_NOTEBOOK_STORAGE=org.apache.zeppelin.notebook.repo.S3NotebookRepo
      - ZEPPELIN_NOTEBOOK_S3_BUCKET=hiroyuki.sano.ninja
      - ZEPPELIN_NOTEBOOK_S3_USER=zeppelin
      - ZEPPELIN_INTERPRETER_OUTPUT_LIMIT=10240000 
    networks:
      mesh:
        aliases:
          - zeppelin.home

networks:
  mesh: {}
