AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Name:
    Type: String
    Default: homepage

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc.yml
      Parameters:
        Name: !Ref Name

  IAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./iam.yml
      Parameters:
        Name: !Ref Name

  SecurityGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./securitygroup.yml
      Parameters:
        EnvironmentName: !Ref Name
        VPC: !GetAtt VPC.Outputs.VpcId

  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./ecs.yml
      Parameters:
        EnvironmentName: !Ref Name
        VPC: !GetAtt VPC.Outputs.VpcId
        Subnets: !GetAtt VPC.Outputs.Subnets
        SecurityGroup: !GetAtt SecurityGroup.Outputs.ECSHostSecurityGroup

  LoadBalancer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./load_balancer.yml
      Parameters:
        EnvironmentName: !Ref Name
        VPC: !GetAtt VPC.Outputs.VpcId
        Subnets: !GetAtt VPC.Outputs.Subnets
        SecurityGroup: !GetAtt SecurityGroup.Outputs.ECSHostSecurityGroup

  Service:
    Type: AWS::CloudFormation::Stack
    DependsOn: LoadBalancer
    Properties:
      TemplateURL: ./service.yml
      Parameters:
        Cluster: !GetAtt ECS.Outputs.Cluster
        VPC: !GetAtt VPC.Outputs.VpcId
        ECSServiceAutoScalingRoleARN: !GetAtt ECS.Outputs.ECSServiceAutoScalingRole
        Listener: !GetAtt LoadBalancer.Outputs.Listener
        Subnets: !GetAtt VPC.Outputs.Subnets
        SecurityGroup: !GetAtt SecurityGroup.Outputs.ECSHostSecurityGroup
