on:
  push:
    branches:
      - 'ga/*'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Container Image
        run: docker version
